# LÀM QUEN VỚI PYTHON

## LÀM QUEN VỚI CÁC THƯ VIỆN
Numpy
Pandas
Matplotlib
Scikit

In [2]:
import numpy as np


In [6]:

My_list = [1,2,3]

In [7]:
arr = np.array(My_list)
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]


In [ ]:
np.array(my_mat)   #Tạo một mảng theo từ đối tượng my_matmat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10,2) #Tạo một mảng số nguyên từ 0 đến 9

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5)) #Tạo một trường giá trị đều là "0", có thể là 1 hàng có thể là 1 ma trậntrận

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,10)   #Tạo ra một dạy số trài dài từ 0 -->5 cách đều nhau mà có 10 con số (10 giá trị)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4)   #Tạo ra một ma trận đơn vị có có kích thước 4x4 (tất cả các phần tử trên đường chéo chính = 1)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(5) #Tạo một hoặc nhiều số ngẫu nhiên trải dài từ 0 --> 1

array([0.02701182, 0.50378178, 0.20049306, 0.38156953, 0.13619235])

In [ ]:
np.random.randn(2) #Tạo các số ngẫu nhiên từ phân phối chuẩn (normal distribution) với trung bình 0 và độ lệch chuẩn 1 (standard normal distribution).

array([-0.4912126 , -1.61563454])

In [27]:
np.sum(my_mat)

np.int64(45)

In [28]:
np.std(my_mat)

np.float64(2.581988897471611)

### Pandas Lib

In [37]:
import pandas as pd
import numpy as np

In [ ]:
labels = ['a','b','c']
my_data = (1,2,3)
arr = np.array(my_data)
d = {'a':1,'b':2,'c':3} # Gán key là a và value là 1


In [32]:
d

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
pd.Series(data=my_data)  #Tạo một mảng dữ liệuliệu

0    1
1    2
2    3
dtype: int64

In [34]:
pd.Series(data=my_data, index = labels)

a    1
b    2
c    3
dtype: int64

In [35]:
pd.Series(my_data,labels)

a    1
b    2
c    3
dtype: int64

In [36]:
from numpy.random import randn

In [ ]:
np.random.seed(101) # Đặt "hạt giống" (seed) cho trình sinh số ngẫu nhiên

In [ ]:
df = pd.DataFrame(randn(5,4),['a','b','c','d','e'], ['x','y','z','t']) # Tạo một đối tượng dataframe
                                                                        # Có 5 hàng 4 cộtcột

In [41]:
df

x         y         z         t
a -0.993263  0.196800 -1.136645  0.000366
b  1.025984 -0.156598 -0.031579  0.649826
c  2.154846 -0.610259 -0.755325 -0.346419
d  0.147027 -0.479448  0.558769  1.024810
e -0.925874  1.862864 -1.133817  0.610478

In [43]:
df['new'] = df['x'] + df['y']

In [44]:
df['new']

a   -0.796464
b    0.869386
c    1.544588
d   -0.332421
e    0.936990
Name: new, dtype: float64

In [45]:
df > 0

x      y      z      t    new
a  False   True  False   True  False
b   True  False  False   True   True
c   True  False  False  False   True
d   True  False   True   True  False
e  False   True  False   True   True

In [46]:
booldf = df>0

In [47]:
df[booldf]

x         y         z         t       new
a       NaN  0.196800       NaN  0.000366       NaN
b  1.025984       NaN       NaN  0.649826  0.869386
c  2.154846       NaN       NaN       NaN  1.544588
d  0.147027       NaN  0.558769  1.024810       NaN
e       NaN  1.862864       NaN  0.610478  0.936990

In [48]:
df.reset_index()

index         x         y         z         t       new
0     a -0.993263  0.196800 -1.136645  0.000366 -0.796464
1     b  1.025984 -0.156598 -0.031579  0.649826  0.869386
2     c  2.154846 -0.610259 -0.755325 -0.346419  1.544588
3     d  0.147027 -0.479448  0.558769  1.024810 -0.332421
4     e -0.925874  1.862864 -1.133817  0.610478  0.936990

In [ ]:
# index level
outside = ['g1','g1','g1','g2','g2','g2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside)) # Ghép cặp phần tử tương ứng của hai danh sách outside và inside, chuyển kết quả thành các danh sách gồm các tupletuple
hier_index = pd.MultiIndex.from_tuples(hier_index) # Tạo một MultiIndex (chỉ số đa cấp) từ một danh sách các tuple.

In [50]:
list(zip(outside,inside))

[('g1', 1), ('g1', 2), ('g1', 3), ('g2', 1), ('g2', 2), ('g2', 3)]

In [51]:
hier_index

MultiIndex([('g1', 1),
            ('g1', 2),
            ('g1', 3),
            ('g2', 1),
            ('g2', 2),
            ('g2', 3)],
           )

In [52]:
df = pd.DataFrame(randn(6,2), hier_index, ['A','B'])

In [53]:
df

A         B
g1 1  0.386030  2.084019
   2 -0.376519  0.230336
   3  0.681209  1.035125
g2 1 -0.031160  1.939932
   2 -1.005187 -0.741790
   3  0.187125 -0.732845

In [55]:
df.loc['g1'].loc[1]

A    0.386030
B    2.084019
Name: 1, dtype: float64

In [60]:
df.index.names = ['Groups','Num']


In [58]:
df

A         B
Groups Num                    
g1     1    0.386030  2.084019
       2   -0.376519  0.230336
       3    0.681209  1.035125
g2     1   -0.031160  1.939932
       2   -1.005187 -0.741790
       3    0.187125 -0.732845

In [62]:
df.loc['g2'].loc[2]['B']

np.float64(-0.7417897046689249)

In [64]:
df.loc['g1']

A         B
Num                    
1    0.386030  2.084019
2   -0.376519  0.230336
3    0.681209  1.035125

In [65]:
df.xs(1, level = 'Num')

A         B
Groups                   
g1      0.38603  2.084019
g2     -0.03116  1.939932

### Missing data solving


In [9]:
d = {'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]}

In [10]:
df = pd.DataFrame(d)

In [11]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [14]:
df.dropna(axis = 1)

C
0  1
1  2
2  3

In [ ]:
df.fillna(value = 'fill value') # đôi khi để xử lý dữ liệu thiếu ta thường fill mean, median,... 

A           B  C
0         1.0         5.0  1
1         2.0  fill value  2
2  fill value  fill value  3

In [ ]:
## ví dụ nè
df['A'].fillna(value=df['A'].median()) #fill median dô nènè

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [22]:
## group by
### group together rows based off of a column
data = {'Company': ['GOOG', 'GOOG','MSFT','MSFT','FB','FB'],
        'Person':['Sam','Charlie','Tom','Bill','Sarah','Carl'],
        'Sales': [200,120,340,124,243,350]}

In [23]:
df = pd.DataFrame(data)

In [24]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Tom    340
3    MSFT     Bill    124
4      FB    Sarah    243
5      FB     Carl    350

In [29]:
by_com = df.groupby('Company')

In [35]:
by_com.sum()

Person  Sales
Company                   
FB        SarahCarl    593
GOOG     SamCharlie    320
MSFT        TomBill    464

In [41]:
df1 = pd.DataFrame({'A': ['A0','A1','A2','A3'],
                    'B': ['B0','B1','B2','B3'],
                    'C': ['C0','C1','C2','C3'],
                    'D': ['D0','D1','D2','D3']},
                    index = [0,1,2,3])

In [42]:
df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6', 'A7'],
    'B': ['B4', 'B5', 'B6', 'B7'],
    'C': ['C4', 'C5', 'C6', 'C7'],
    'D': ['D4', 'D5', 'D6', 'D7']
}, index=[4, 5, 6, 7])


In [43]:
df3 = pd.DataFrame({
    'A': ['A8', 'A9', 'A10', 'A11'],
    'B': ['B8', 'B9', 'B10', 'B11'],
    'C': ['C8', 'C9', 'C10', 'C11'],
    'D': ['D8', 'D9', 'D10', 'D11']
}, index=[8, 9, 10, 11])


#### Kỹ năng merge and concatenating
##### merge sẽ gom cột như excel nhưng maybe sẽ dễ làm hơn (code ít hơn), vẫn theo logic của sql thôi
- | `'inner'`  | Chỉ giữ **các hàng trùng khóa** ở cả `left` và `right`. Giống `INNER JOIN` trong SQL                          |
- | `'outer'`  | Lấy **toàn bộ các hàng** từ cả `left` và `right`. Thiếu giá trị sẽ được điền bằng NaN. Giống `FULL OUTER JOIN`. |
- | `'left'`   | Giữ **toàn bộ hàng** của `left`, khớp dữ liệu từ `right` nếu có. Giống `LEFT Joint'                        |
- | `'right'`  | Giữ **toàn bộ hàng** của `right`, khớp dữ liệu từ `left` nếu có. Giống `RIGHT JOIN`.    
##### Concatenating (hay “nối”) là quá trình kết hợp nhiều DataFrame (hoặc Series) với nhau theo chiều dọc (trục 0) hoặc theo chiều ngang (trục 1) mà không cần dựa trên cột khóa (key), khác với merge!
- axis = 0 thêm hàng (nối cột)
- axis = 1 thêm cột  (nối hàng)
##### Join sẽ khác với merge ở chỗ join sẽ mặc đinh theo index còn merge có thể theo ai cũng đc (on= ...)


In [ ]:
  pd.concat([df1,df2,df3]) # Concatenation glues together DataFrameDataFrame

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [ ]:
pd.concat([df1,df2,df3], axis=1) # axis theo chiều ngang

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [47]:
left = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})

right = pd.DataFrame({
    'key': ['K0', 'K1', 'K2', 'K3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})


In [48]:
pd.merge(left,right, how = 'inner', on = 'key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [49]:
left = pd.DataFrame({
    'key1': ['K0', 'K0', 'K1', 'K2'],
    'key2': ['K0', 'K1', 'K0', 'K1'],
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
})
right = pd.DataFrame({
    'key1': ['K0', 'K1', 'K1', 'K2'],
    'key2': ['K0', 'K0', 'K0', 'K0'],
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
})


In [ ]:
pd.merge(left,right, on = ['key1']) # 'on' là điều kiện để merge

key1 key2_x   A   B key2_y   C   D
0   K0     K0  A0  B0     K0  C0  D0
1   K0     K1  A1  B1     K0  C0  D0
2   K1     K0  A2  B2     K0  C1  D1
3   K1     K0  A2  B2     K0  C2  D2
4   K2     K1  A3  B3     K0  C3  D3

In [52]:
pd.merge(left,right, how = 'outer',on = ['key1','key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K0  NaN  NaN   C3   D3
5   K2   K1   A3   B3  NaN  NaN

In [53]:
pd.merge(left,right, how = 'right',on = ['key1','key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [61]:
left = pd.DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B': ['B0', 'B1', 'B2', 'B3']
}, index = ['k0', 'k1','k2', 'k4'])
right = pd.DataFrame({
    'C': ['C0', 'C1', 'C2', 'C3'],
    'D': ['D0', 'D1', 'D2', 'D3']
}, index = ['k0', 'k1','k2', 'k3'])

In [62]:
left.join(right)

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1   C1   D1
k2  A2  B2   C2   D2
k4  A3  B3  NaN  NaN

### Read data
thường sẽ lỗi khi copy quăng dô và link nó có tiền tố như c: 'ổ C' --> thêm r trước đó hoặc đổi '\' sang '\\'

In [63]:
pwd

'c:\\Users\\USER\\AppData\\Local\\Programs\\Microsoft VS Code'

In [68]:
pd.read_excel(r'c:\Users\USER\Downloads\Call Centre Data_Integrated (2).xlsx')

time  length forwarded  customer_satisfaction  waiting    problem  \
0          2     227       NaN                   10.0       24   delivery   
1          3     288       NaN                    7.0        0   delivery   
2          3     189       NaN                    7.0       54   delivery   
3          3     206       NaN                    9.0      282   delivery   
4          3     261       NaN                    NaN      151   delivery   
...      ...     ...       ...                    ...      ...        ...   
150932    24     364       NaN                    5.0      143  complaint   
150933    24     453       NaN                    4.0      113   delivery   
150934    24     161       NaN                    NaN        0   delivery   
150935    24      62       NaN                    9.0        0   delivery   
150936    24     380       NaN                    8.0        0   delivery   

        agent  
0          58  
1          19  
2          53  
3          95  
4         113  
...       ...  
150932     58  
150933     65  
150934     77  
150935    109  
150936     52  

[150937 rows x 7 columns]

In [78]:
df.to_csv('My_output')

In [75]:
pd.read_csv('My_output')

Unnamed: 0 Company   Person  Sales
0           0    GOOG      Sam    200
1           1    GOOG  Charlie    120
2           2    MSFT      Tom    340
3           3    MSFT     Bill    124
4           4      FB    Sarah    243
5           5      FB     Carl    350

In [79]:
data = pd.read_html('https://cafef.vn/du-lieu.chn')

In [80]:
type(data)

list

In [82]:
data[1]

Empty DataFrame
Columns: [STT, Mã CK, KL mua ròng, Giá, Thay đổi]
Index: []